obj-$(CONFIG_MMCOOPS)		+=mmcoops.o
obj-$(CONFIG_WDT_LOG)		+=wdt_log.o
obj-$(CONFIG_WDT_DETECT_LG1K)	+=wdt_detect_lg1k.o
obj-$(CONFIG_WDT_DETECT_RTK)    +=wdt_detect_rtk.o
obj-$(CONFIG_LL_MMC)		+=ll_mmc.o
obj-$(CONFIG_LL_MMC_LG1K)	+=ll_mmc_lg1k.o
