obj-$(CONFIG_LGTV_DRIVER_PROCFS_SUPPORT)   += procfs.o
obj-$(CONFIG_LGTV_DRIVER_PROCFS_SUPPORT)   += ext-in-hdmi.o
obj-$(CONFIG_LGTV_DRIVER_PROCFS_SUPPORT)   += ext-in-adc.o
obj-$(CONFIG_LGTV_DRIVER_PROCFS_SUPPORT)   += ext-in-avd.o