
rdvb-ca-y += rdvb_ca.o \
		rdvb_ca_parse.o

obj-y += rdvb-ca.o
obj-y += rdvb_ca_sys.o

ccflags-y += -Idrivers/media/dvb-core/
ccflags-y += -Idrivers/rtk_kdriver/rdvb
ccflags-y += -Idrivers/rtk_kdriver/pcmcia

