obj-$(CONFIG_SPI_PL022)		+= spi.o
obj-$(CONFIG_ETHERNET)		+= eth.o
obj-$(CONFIG_USB)		+= usb.o
obj-$(CONFIG_AMBA_PL08X)	+= dmac.o
obj-$(CONFIG_CMA)		+= cma.o
obj-$(CONFIG_LG_SNAPSHOT_BOOT)		+= snap.o
obj-y	+= mach.o
obj-$(CONFIG_PM)		+= pm.o
