
rdvb-dmx-y += rdvb_dmx.o \
		rdvb_dmx_filtermgr.o \
		rdvb_dmx_ctrl.o \
		dmx_filter.o \
		dmx_parse_context.o \
		sys.o \
		fullcheck.o \
		LinearRegression.o \
		pvr.o \
		pcrsync.o \
		parser.o \
		sdec.o \
		sdec_ecp.o \
		refclk.o \
		pcrdebugger.o \
		pcrtracking.o \
		debug.o \
		descrambler.o \
		dmx_inbandcmd.o \
		dmx_service.o

obj-y += rdvb-dmx.o


ccflags-y += -Idrivers/media/dvb-core/
ccflags-y += -Idrivers/rtk_kdriver/rdvb
