rdvb-dmxbuf-y  += rdvb_dmx_buf.o dmx_buf_misc.o dmx_buf.o dmx_buf_mgr.o sys.o dmx_buf_dbg.o

obj-y += rdvb-dmxbuf.o


ccflags-y += -Idrivers/rtk_kdriver/rdvb
ccflags-y += -Idrivers/rtk_kdriver/include
ccflags-y += -Idrivers/media/dvb-core/