
rdvb-acas-y += rdvb_acas.o \
        rdvb_acas_atr.o \
        rdvb_acas_session_t1.o \
        rdvb_acas_debug.o 

obj-y += rdvb-acas.o


ccflags-y += -Idrivers/media/dvb-core/
ccflags-y += -Idrivers/rtk_kdriver/rdvb
ccflags-y += -Idrivers/rtk_kdriver/smartcard
