# Makefile for the Realtek scaler VIP ko drivers.

#CROSS="../../../../../../../system/tmp/toolchain/x86_64-starfishsdk-linux_5.0.0/sysroots/x86_64-starfishsdk-linux"

#all:
#	make ARCH=arm CROSS_COMPILE=$(CROSS) KCPPFLAGS="$(CPPFLAGS)" -C $(KERNEL) SUBDIRS=$(PWD) modules
#clean:
#	make ARCH=arm CROSS_COMPILE=$(CROSS) KCPPFLAGS="$(CPPFLAGS)" -C $(KERNEL) SUBDIRS=$(PWD) clean

#KBUILD_EXTRA_SYMBOLS=/home4/elitsai/KxL/kernel/linux/linux-4.4.3/Module.symvers

obj-m := GSR_module_Verify.o	



	
