
rdvb-ca-plus-y += rdvb_cip_dev.o
rdvb-ca-plus-y += rdvb_cip_ctrl.o

obj-y += rdvb_cip_dev.o
obj-y += rdvb_cip_ctrl.o

ccflags-y += -Idrivers/media/dvb-core/
ccflags-y += -Idrivers/rtk_kdriver/rdvb
ccflags-y += -Idrivers/rtk_kdriver/tp
ccflags-y += -Idrivers/rtk_kdriver/include/rtk_kdriver/
