ccflags-y		:= -Idrivers/block/zram/

obj-$(CONFIG_WEBOS)		+= webos.o
obj-$(CONFIG_LOW_MEM_NOTIFY)	+= low-mem-notify.o
obj-$(CONFIG_SYSRQ_LOG_PRINT)	+= sysrq.o
obj-$(CONFIG_KMSG_RAW)		+= kmsg_raw.o
obj-$(CONFIG_USER_INITCALL)	+= user_initcall.o
obj-$(CONFIG_FAULT_NOTIFIER)	+= fault_notifier.o
obj-$(CONFIG_GPU_INFO)		+= gpuinfo.o
obj-$(CONFIG_MRI_HELPER)	+= mri_helper.o
obj-$(CONFIG_BLOCK_DUMP_MSG)	+= block_dump_msg.o

obj-y				+= logger/
