# Makefile for the Realtek scaler related drivers.
#
obj-y += vsc_v4l2_driver.o vsc_v4l2_cb_api.o vbe_v4l2_driver.o vbe_v4l2_cb_api.o vt_v4l2_driver.o vt_v4l2_cb_api.o  vbi_v4l2_driver.o vbi_v4l2_cb_api.o



