#ifndef __V4L2_VENC_CONF_H__
#define __V4L2_VENC_CONF_H__

#define VDEC_CONF_FRM_MSG_CNT 512
#define VDEC_CONF_MSGQ_ENTRY_CNT 16
#define VDEC_CONF_USERDATAQ_SIZE 20480
#define VDEC_CONF_TASK_MSECS 10

#define NUM_OF_FRAME_BUFFER     4
#define VENC_ENC_RBSIZE_STREAM  0x1000000
#define VENC_ENC_RBSIZE_MESSAGE 0x2000
#define VENC_DIN_RBSIZE_STREAM  0x1000000//(sizeof(unsigned long) * NUM_OF_FRAME_BUFFER)
#define VENC_DIN_RBSIZE_COMMAND 0x2000

#define VENC_DIN_RB_PIN 1
#define VENC_Enc_RB_PIN 0

#endif
